### ISSUE TITLE
Need illustrator open .ait script

### ISSUE THREAD

**Issue by sgops27** [AlexanderLyon/Illustrator-Scripts#1]
I have created some illustrator template files (.ait) placed in my local D drive (path),
Ex: 00_Helvetica_27 x 40, 00_Helvetica_28 x 47 (and Many)

once I run the script open that popup template file (attached i create the screenshot) window and select what file i need then hit OK open that file.

it's passable in javascript
![WhatsApp Image 2019-02-28 at 9 57 11 AM](https://user-images.githubusercontent.com/47688301/54737008-e98c9d00-4bd3-11e9-8908-02fe08052a2b.jpeg)

**Comment by AlexanderLyon** [comment]
Are you referring to a file select dialog? The "Export Symbols to AI.js" script is the only one that implements what I think you're looking for: upon running the script you're shown a window that lets you select an .AI file to open. Unfortunately this isn't using Illustrator's native UI as shown in your screenshot. If you're able to accomplish that feel free to fork!

**Comment by sgops27** [comment]
Actually, my team is more than 15 peoples, so we need quality and consistency fonts and font size, many things, i have fixed all in our template files (.ait). that files placed in server path Ex:\\172.24.161.52\books\Template (already we have used the 
script attached here but that script decoded) my old server some space problem, (we need more sapce) so they are allocated the new server in my team, now that script is not working we unable to change server path that script it's decoded so pls help me.
[Template.zip](https://github.com/AlexanderLyon/Illustrator-Scripts/files/2994841/Template.zip)

**Comment by AlexanderLyon** [comment]
This does not sound like an issue related to one of the scripts in this repo. Adobe provides [comprehensive documentation](https://wwwimages2.adobe.com/content/dam/acom/en/devnet/illustrator/pdf/Illustrator_JavaScript_Scripting_Reference_2017.pdf) for scripting using Javascript that may help you.
